default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index"}
  methods: GET

default_login_usuario:
  path: /login_usuario
  defaults: { _controller: "AppBundle:Default:loginUsuario"}
  methods: POST

default_login_restaurante:
  path: /login_restaurante
  defaults: { _controller: "AppBundle:Default:loginRestaurante"}
  methods: POST

default_pruebas:
  path: /pruebas
  defaults: { _controller: "AppBundle:Default:pruebas"}
  methods: POST
