BackendBundle\Entity\Combo:
    type: entity
    table: combos
    indexes:
        fk_categoria_combo:
            columns:
                - idCategoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        precio:
            type: float
            nullable: true
            precision: 255
            scale: 2
    manyToOne:
        categoria:
            targetEntity: Categoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCategoria:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
