BackendBundle\Entity\Evento:
    type: entity
    table: eventos
    indexes:
        fk_restautante_evento:
            columns:
                - idRestaurante
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        restaurante:
            targetEntity: Restaurante
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idRestaurante:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
