BackendBundle\Entity\Ingrediente:
    type: entity
    table: ingredientes
    indexes:
        fk_restautante_ingrediente:
            columns:
                - idRestaurante
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        precio:
            type: float
            nullable: true
            precision: 255
            scale: 2
    manyToOne:
        restaurante:
            targetEntity: Restaurante
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idRestaurante:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
